blank_issues_enabled: true
contact_links:
  - name: Report translation issue
    url: https://translate.fluentautoclicker.com
    about: Help improve translations on Crowdin
  - name: Get community support
    url: https://github.com/RyanLua/FluentAutoClicker/discussions
    about: Get support/help from the GitHub Discussions community
