blank_issues_enabled: true
contact_links:
  - name: Get Community Support
    url: https://github.com/RyanLua/FluentAutoClicker/discussions
    about: Get support/help from the GitHub Discussions community.
